### ISSUE TITLE
async/await?

### ISSUE THREAD

**Issue by vindarel** [BnMcGn/paren6#1]
Hello,

How can we write async/await functions with Parenscript? The expected result is

```
async function foo(){
  await bar();
}
```

It would be a good fit for paren6, right? If so, do you have an idea how to add it? I just skimmed through ps macros.

Thanks

**Comment by BnMcGn** [comment]
I imagine it would be a good fit. I'll have a look at it.

**Comment by BnMcGn** [comment]
Okay, here's the homework so far...

It should be pretty simple to reuse the code from [es5-async-await](https://github.com/bakerface/es5-async-await) except that it needs Promise and fibers/future. 

At the moment, there is no good system for requesting dependencies for a parenscript library. So until I or some other volunteer comes up with such a system, we're left with telling the user to manually require them. Awkward but possible.

There are some babel plugins from which technique could be borrowed: [regenerator](http://facebook.github.io/regenerator/) implements generators for ES5. [Fast-async](https://www.npmjs.com/package/fast-async) manages to implement async/await entirely with promises.

My babel-plugin-fu is not strong. I'm not sure how easy it would be to translate either of these approaches into parenscript. Nor is it evident that they can be implemented without dependencies.

Vindarel, are you interested in implementing this? Personally, I have mixed feelings. It would be fun, but also might involve more homework than I want to take on ATM.

**Comment by vindarel** [comment]
uhoh. I'm surprised by the mention of es5-async-await, babel and all. I was thinking that we'd need to define one or two Parenscript macros, so we could write something like:

```
(ps:ps
  (ps:defasync foo ()
    (ps:await (bar)))
```

which would be turned to the JS above.

**Comment by svetlyak40wt** [comment]
Guys, it would be cool to implement `async/await`. @vindarel did you find some workaround?

**Comment by vindarel** [comment]
I just found this implementation of async/await: https://github.com/Junker/paren-async (source https://gist.github.com/ralt/57a3811ca7ed734295e87393b9964cbe)

(found it after I saw that @svetlyak40wt you starred a couple repos of this person)

related: https://github.com/Junker/paren-jquery

**Comment by BnMcGn** [comment]
Ok, thanks.

I'll add a link to paren-async in the docs
