### ISSUE TITLE
Calling (super) inside constructor does not work

### ISSUE THREAD

**Issue by monomon** [BnMcGn/paren6#3]
The result looks like
```
function menuWithButtons() {
    __PS_MV_REG = [];
    return super();
};
menuWithButtons.prototype = Object.create(HTMLElement.prototype);
menuWithButtons.prototype.constructor = menuWithButtons;
...
```
The browser complains
```
Uncaught SyntaxError: super() is only valid in derived class constructors
```
I am guessing because the function is not a proper class?
Or am I missing anything with calling `super`?

**Comment by BnMcGn** [comment]
Defclass6 is a macro, and super is a macrolet within it. As such 'super()' shouldn't ever show up in your JS code. It looks like you included a parent class, so super should be defined. Maybe the paren6 package is not in your 'use' list. Qualify the call to super with the package name: (paren6:super ...) 

Hope that helps!

**Comment by monomon** [comment]
Thanks I'll give this a try.

**Comment by monomon** [comment]
This worked, sorry for the noise. I somehow did not think this symbols would be interned.
